[toolchain]

[features]
resolution = true
skip-lint = false

[programs.mainnet]
jailbreak_pool = "CZCDUg5qie9vCU5yK2ByUcdAtUtoBc2vPVAHFgi42MrF"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Mainnet"
wallet = "~/.config/solana/key.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
